((nil . ((eval . (setq-local org-directory (expand-file-name (locate-dominating-file default-directory ".dir-locals.el"))))
         (eval . (setq-local org-id-locations-file (expand-file-name ".org-id-locations" org-directory)))
         (eval . (setq-local org-roam-directory org-directory))
         (eval . (setq-local org-roam-db-location (expand-file-name  ".org-roam.db" org-roam-directory)))
         (eval . (setf citar-bibliography (list (expand-file-name "bibliography/references.bib" org-directory))))
         (eval . (setf org-cite-global-bibliography (list (expand-file-name "bibliography/references.bib" org-directory))))
         (org-html-doctype "xhtml5")
         (org-html-html5-fancy t)
         (org-html-link-org-files-as-html t)
         (org-html-prefer-user-labels t)
         (org-html-validation-link nil)
         (org-html-head "<link rel=\"stylesheet\" type=\"text/css\" href=\"/personal-notes-public/main.css\" />")
         (org-html-head-include-default-style nil)
         (org-html-checkbox-type 'unicode)
         (org-html-with-latex 'mathjax)
         (org-html-text-markup-alist '((bold . "<b>%s</b>")
                                       (code . "<code>%s</code>")
                                       (italic . "<i>%s</i>")
                                       (strike-through . "<del>%s</del>")
                                       (underline . "<span class=\"underline\">%s</span>")
                                       (verbatim . "<pre class=\"verbatim\">%s</pre>")))
         (org-html-preamble "<nav aria-labelledby=\"nav-head-main\">\n<h1 id=\"nav-head-main\">Navigation</h1>\n<ul>\n<li><a href=\"/personal-notes-public/\" title=\"Home\">Home</a></li>\n<li><a href=\"/personal-notes-public/directory.html\" title=\"Directory\">Directory</a></li>\n</ul>\n</nav>")
         (org-html-footnotes-section "<section id=\"footnotes\">\n<h2 class=\"footnotes\">%s: </h2>\n<div id=\"text-footnotes\">\n%s\n</div>\n</section>")
         (org-html-postamble "<footer>\n<p class=\"date\">Last Modified: %C</p>\n<p class=\"author\">Author: %a</p>\n</footer>")
         (org-export-with-broken-links :mark)
         (org-export-with-properties '("ROAM_REFS" "ROAM_ALIASES")))))
