name: Publish Org Mode/Roam notes

on:
  push:
    branches:
      - public

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Export Org Mode files
        uses: tecosaur/org-knit-action@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config: https://github.com/Ryan-B-W/vimacs.app.git
          export: html
          eval: true
          branch: gh-pages
